extends Node

var pressingWorld = {
	Enums.TEMPORARY_SAVE_PRESSING.COUNTER: 0,
	Enums.TEMPORARY_SAVE_PRESSING.FRUIT_ENUM: null,
	Enums.TEMPORARY_SAVE_PRESSING.FRUIT_PV: null,
	Enums.TEMPORARY_SAVE_PRESSING.WEAPON: null,
	Enums.TEMPORARY_SAVE_PRESSING.FRUIT_BAR_ARRAY: null,
	Enums.TEMPORARY_SAVE_PRESSING.BACKGROUND_COLOR_FAZE: null,
	Enums.TEMPORARY_SAVE_PRESSING.MUSIC_NB: null,
	Enums.TEMPORARY_SAVE_PRESSING.PLAYBACK_POSITION: null
}
